domain_list = [
'YAHOO.CO.IN', 'musaliarcollege.com', 'matsuniversity.ac.in', 'MBITS.EDU.IN', 'ddu.du.ac.in',
'btcc.ac.in', 'kjit.org', 'hcet.gtc.ac.in', 'arsd.du.ac.in', 'mangalam.in', 'growmore.ac.in',
'snit.edu.in', 'nmitkerala.ac.in', 'bitraipur.ac.in', 'aitdgoa.edu.in', 'dishamail.com', 'cemk.ac.in',
'titsbhiwani.ac.in', 'sist.in', 'fossee.in', 'sandurgroup.com', 'eranadknowledgecity.com', 'bsnl.in',
'ieee.org', 'lbsim.ac.in', 'bnmit.in', 'echeloninstitute.com', 'jecc.ac.in', 'stisttvm.edu.in',
'accordbschool.com', 'gdgoenka.ac.in', 'vjcet.org', 'paacet.com', 'gmail.com', 'gecbharuch.com',
'socet.edu.in', 'jntua.ac.in', 'pinnacle.ac.in', 'yahoo.co.in', 'opjit.edu.in', 'icet.ac.in', 'mbcet.org',
'galaxyglobaledu.com', 'cppfhscc.org', 'toms.ac.in', 'secab.org', 'qiscet.edu.in', 'iitg.ernet.in',
'yahoo.co.uk', 'rajguru.du.ac.in', 'bvmengineering.ac.in', 'cuh.ac.in', 'cesociety.in', 'vjec.ac.in',
'iitmipu.ac.in', 'mangaloreuniversity.ac.in', 'gujaratuniversity.ac.in', 'igmt.org',
'vignanuniversity.org', 'teriuniversity.ac.in', 'unigoa.ac.in', 'nshm.com', 'andc.du.ac.in',
'spuvvn.edu', 'stcet.net', 'utu.ac.in', 'mirandahouse.ac.in', 'jamiahamdard.ac.in',
'providencecollege.org', 'kazirangauniversity.in', 'cimage.in', 'nova.ac.in', 'sjcetpalai.ac.in',
'mbict.ac.in', 'vedavyasa.org', 'sbce.ac.in', 'prabhujagatbandhucollege.edu.in', 'nitgoa.ac.in',
'kuk.ac.in', 'vidyaacademy.ac.in', 'aryanet.org', 'yahoo.com', 'mesitam.ac.in', 'macev.org',
'rungta.ac.in', 'sigma.ac.in', 'rediffmail.com', 'iesce.info', 'gmit.ac.in', 'anjarakandy.in',
'iitgn.ac.in', 'marian.ac.in', 'mvn.edu.in', 'mait.ac.in', 'svpcet.org', 'raiuniversity.edu',
'kmpce.org', 'svcolleges.edu.in', 'live.com', 'charusat.ac.in', 'gtu.edu.in', 'bccaarmel.ac.in',
'moderneducationgroup.in', 'universalcollege.net', 'kssem.edu.in', 'sbpedu.org.in', 'ammini.edu.in',
'mbcpeermade.com', 'zhi.org.in', 'sngce.ac.in', 'saintgits.org', 'jaibharathengg.com', 'gcet.ac.in',
'tistcochin.edu.in', 'chowgules.ac.in', 'srit.ac.in', 'tkmit.ac.in', 'hotmail.com', 'sgi.ac.in',
'KRGCE.IN', 'mcetonline.com', 'nvpas.edu.in', 'paruluniversity.ac.in', 'scmsgroup.org', 'anangpuria.com',
'musaliarcollegeckl.in', 'nirmauni.ac.in', 'christuniversity.in', 'rocketmail.com', 'scet.ac.in',
'sal.edu.in', 'djmit.ac.in', 'apexuniversity.edu.in', 'pvpsiddhartha.ac.in', 'krmangalam.edu.in',
'bciit.ac.in', 'awhengg.org', 'ssipmt.com', 'csitdurg.in', 'mookambika.ac.in', 'kswu.ac.in', 'glsict.org',
'yahoo.in', 'indusuni.ac.in', 'songadhashram.org', 'gimt-guwahati.ac.in', 'visat.ac.in', 'yit.ac.in',
'jainpolytechnic.in', 'royalcet.ac.in', 'srcem.ac.in', 'gctohana.gov.in', 'jcmcsiit.ac.in', 'hcet.in',
'git.edu', 'sgtengineeringcollege.org', 'sssihl.edu.in', 'meaec.edu.in', 'ycet.ac.in', 'nic.in',
'rgi.edu.in', 'sngist.org', 'riet.edu.in', 'fisat.ac.in', 'gdec.in', 'msit.in', 'dbuniversity.ac.in',
'jagannath.org', 'christknowledgecity.com', 'mmumullana.org', 'jagannathuniversityncr.ac.in', 'iibm.in',
'jaigroup.in', 'ymail.com', 'patnawomenscollege.in', 'mail.com', 'ucet.in', 'snmimt.edu.in',
'kmeacollege.ac.in', 'dibru.ac.in', 'jimsindia.org', 'ggnindia.dronacharya.info', 'muthootgroup.com',
'gperi.ac.in', 'HOLYKINGSCOLLEGE.COM', 'mits.ac.in', 'ncuindia.edu', 'brcm.edu.in', 'vidyatcklmr.ac.in',
'svtm.in'
]
